version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: demo-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: demo-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
