name: Push Code to S3

on:
  push:
    branches:
      - main  

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Zip project
      run: |
        echo "Zipping all files including hidden and large folders..."
        # Exclude .git and GitHub workflow files to avoid unnecessary size
        zip -r new.zip . -x "*.git*" -x "*.github/*"
        # Optional: check the zip size
        ls -lh new.zip

    - name: Upload to S3
      run: aws s3 cp new.zip s3://zip-demo123/new.zip
